### ISSUE TITLE
Error in rsa-key-generation image

### ISSUE THREAD

**Issue by iupsilon** [Sambego/jose-presentation#2]
Hi,
I saw you wonderful presentation in Verona on April 22nd.
I really appreciated it and I would like to report a little imprecision I found in the image:

jose-presentation/src/img/rsa-key-generation.svg

RSA Private Key
Private exponent (d): e (mod lambda(n)) 

Inverse simbol is missing:
e*d = 1 mod(lambda(n)) -> d = inverse(e) mod(lambda(n))

**Comment by Sambego** [comment]
Great catch, thanks for reporting the error!

It's now fixed: https://jose.sambego.tech/62
